name: oauth_dio
description: A customizable oauth client with token storage and interceptors for dio
version: 0.2.2+3
homepage: https://github.com/salomaosnff/oauth_dio

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0
